name: lifetrack
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  intl: ^0.19.0
  table_calendar: ^3.0.9
  url_launcher: ^6.2.1  # This is used for launching URLs like phone, email, etc.
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0
  http: ^1.2.2  # For making HTTP requests
  mysql1: ^0.20.0  # For interacting with MySQL directly (useful for client-side interaction, but it's better to use backend APIs)
  bcrypt: ^1.1.3
  fl_chart: ^0.69.2
  flutter_svg: ^2.0.16
  flutter_html: ^3.0.0-beta.2
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

# Splash screen configuration
flutter_native_splash:
  color: "#4A628A"
  image: assets/splash.png
  android: true
  ios: true
  web: false

  # You can add custom images or fonts if required:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Fonts section (uncomment and configure if needed)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
